#
#   Stuff to help to copy file to remote computer.
#
function Copy-RemoteItem {
[CmdletBinding()]
Param(
    [Parameter(ValueFromPipeline=$true, ValueFromPipelineByPropertyName=$true, Mandatory=$true, Position=0)]    
    [String]$Path,
    [String]$ComputerName,
    $Credential,
    $Session
)
    $fileName = [IO.Path]::GetFileName($Path)
    $data = Get-Content $Path -Encoding Byte
    $encodedData = [Convert]::ToBase64String($data)    
    

    $tmpScriptFile = [IO.Path]::ChangeExtension([IO.Path]::GetTempFileName(), ".ps1")
    $script = "Set-Content " + $fileName + " -Encoding Byte ( [Convert]::FromBase64String(""" + $encodedData + """) )"
    
    Set-Content $tmpScriptFile $script
    
    if ($Session -ne $null){
        Invoke-Command $tmpScriptFile -Session $Session
    } else {
	    Invoke-Command $tmpScriptFile -ComputerName $ComputerName -Credential $Credential
    }
    
    Remove-Item $tmpScriptFile -Force -ErrorAction SilentlyContinue
	
<#
.Synopsis
    Copies file to remote computer.
.Description     
    Using PowerShell Remoting command copies any local file to the remote host. Most often you can find copied file in your remote Documents directory.
.Parameter Path
    Specifies the path to an item. Copy-RemoteItem retrieves the content of the item.
.Parameter ComputerName
    Specifies the computers on which the command runs.
.Parameter Credential
    Specifies a user account that has permission to perform this action.

    Type a user name, such as "User01" or "Domain01\User01", or enter a variable that contains a PSCredential object, such as one generated by the Get-Credential cmdlet. When you type a user name, you will be prompted for a password.   
.Parameter Session
    Specifies a remoting session to use.
    
.Example
    Copy-RemoteItem Tests.ps1 -Credential "Comp1\User01" -ComputerName "Comp1"

    Description
    -----------
    Copy file Tests.ps1 to the Docmuents folder of the User01 on computer Comp1
.Example
    $session = New-PsSession -Credential "Comp1\User01" -ComputerName "Comp1"
    Copy-RemoteItem Tests.ps1 -Session $session

    Description
    -----------
    Copy file Tests.ps1 using shared session
#>
}

Export-ModuleMember Copy-RemoteItem
